// Code generated by go2go; DO NOT EDIT.


//line constraints.go2:1
package gtl

//line constraints.go2:1
import (
//line constraints.go2:1
 "errors"
//line constraints.go2:1
 "reflect"
//line constraints.go2:1
 "testing"
//line constraints.go2:1
)

//line constraints.go2:1
type Importable୦ int

//line constraints.go2:1
var _ = errors.As
//line constraints.go2:1
var _ = reflect.Append
//line constraints.go2:1
var _ = testing.AllocsPerRun
