name: Build & Test workflow

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_test:
    runs-on: ubuntu-latest
    container: golang:1.17.2
    steps:
      - uses: actions/checkout@v2

      - name: Run build & test
        run: |
          go install golang.org/dl/gotip@latest
          gotip download
          gotip test ./containers/*/ -v
          gotip test ./utility -v
